Repository altafshaikh/make-your-first-contribution, pull requests merged in 2020-10, with the labels that each got.

#16 first contribution
  about me.txt
Labels: reviewing

#25 added details
  index.html
Labels: reviewing

#27 Update index.html
  index.html
Labels: reviewing

#29 Update index.html
  index.html
Labels: reviewing

#31 added my detail
  index.html
Labels: reviewing

#33 Added Meta tags and Favicon and footer
  android-chrome-192x192.png
  android-chrome-512x512.png
  apple-touch-icon.png
  favicon-16x16.png
  favicon-32x32.png
  index.html
Labels: reviewing

#34 Added My Detail
  index.html
Labels: hacktoberfest-accepted, reviewing

#37 Update index.html
  index.html
Labels: hacktoberfest-accepted, reviewing

#38 Added yusril profile
  index.html
Labels: hacktoberfest-accepted

#39 Hello World
  index.html
Labels: hacktoberfest-accepted
